### ISSUE TITLE
Not compatible with the latest conan(1.22.0)

### ISSUE THREAD

**Issue by vinnamkim** [adamrehn/conan-ue4cli#3]
`ue4 conan build` with the latest conan(1.22.0) makes an error as follows. It seems an recently added feature of conan in 1.22.0: [`from conans.tools import _global_config as config`](https://github.com/conan-io/conan/blob/842af76cac915c5bfb55750096e5f0bd9eb001d0/conans/client/tools/net.py#L55) isn't set properly.

Related to https://github.com/adamrehn/ue4-docker/issues/66

Traceback (most recent call last):
  File "/usr/local/bin/ue4", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ue4cli/cli.py", line 216, in main
    SUPPORTED_COMMANDS[command]['action'](manager, args)
  File "/usr/local/lib/python3.6/dist-packages/conan_ue4cli/main.py", line 34, in main
    SUBCOMMANDS[subcommand]['function'](manager, args[1:])
  File "/usr/local/lib/python3.6/dist-packages/conan_ue4cli/build.py", line 302, in build
    update(manager, argv)
  File "/usr/local/lib/python3.6/dist-packages/conan_ue4cli/update.py", line 7, in update
    RecipeCache.updateCache()
  File "/usr/local/lib/python3.6/dist-packages/conan_ue4cli/RecipeCache.py", line 36, in updateCache
    tools.get(RECIPE_ZIP_URL, destination=parentDir)
  File "/usr/local/lib/python3.6/dist-packages/conans/tools.py", line 81, in get
    return tools_net.get(output=_global_output, requester=_global_requester, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/conans/client/tools/net.py", line 21, in get
    md5=md5, sha1=sha1, sha256=sha256)
  File "/usr/local/lib/python3.6/dist-packages/conans/client/tools/net.py", line 58, in download
    retry = retry if retry is not None else config.retry
AttributeError: 'NoneType' object has no attribute 'retry'

**Comment by adamrehn** [comment]
This is now fixed in conan-ue4cli version 0.0.17, which will work with both Conan 1.21 and Conan 1.22.
